### ISSUE TITLE
Flowpipe crashed when passing wrong param in step block

### ISSUE THREAD

**Issue by Priyanka-Chatterjee-2000** [turbot/flowpipe#140]
```
flowpipe-mod-discord % flowpipe service start
panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
github.com/turbot/flowpipe/pipeparser/error_helpers.FailOnError({0x12c146bc8, 0x140009a75f0})
	/home/runner/work/flowpipe/flowpipe/flowpipe/pipeparser/error_helpers/utils.go:33 +0x54
github.com/turbot/flowpipe/internal/cmd/service.ServiceStartCmd.startManagerFunc.func1(0x1400091c800?, {0x104a36c00?, 0x4?, 0x1033d605d?})
	/home/runner/work/flowpipe/flowpipe/flowpipe/internal/cmd/service/start.go:71 +0x98
github.com/spf13/cobra.(*Command).execute(0x140005ae900, {0x104a36c00, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x640
github.com/spf13/cobra.(*Command).ExecuteC(0x140005ae300)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/turbot/flowpipe/internal/cmd.RunCLI({0x103cfcff8?, 0x14000645380?})
	/home/runner/work/flowpipe/flowpipe/flowpipe/internal/cmd/cmd.go:14 +0x2c
main.main()
	/home/runner/work/flowpipe/flowpipe/flowpipe/main.go:38 +0x248
```

**Comment by vhadianto** [comment]
Verified in v0.3 main this issue is no longer valid. We have the following parse error:

```
Bad Request: invalid property path: pram.name
```

if there's an invalid reference to param/resources.
